---
- hosts: all
  become: true
  become_user: root
  tasks:
  
  - name: shutdown the system
    command: poweroff
    when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

