---
- hosts: all
  become: true
  become_user: root
  tasks:
   - name: show the ansible
     debug: 

         msg: 
                   The Default address of {{ ansible_fqdn }} is {{ ansible_default_ipv4.address }}
