---
- hosts: all
  become: true
  become_user: root
  tasks:
  - name: install httpd package
    yum:
      name: httpd
      state: latest
      notify: restart httpd
      

  handlers:
    - name: restart apache
      service: 
        name: httpd
        state: restarted 



