---
- hosts: all
  become: true
  become_user: root
  gather_facts: false
  
  vars:
    web_pkg: httpd
    firewall_pkg: firewalld
    perl_pkg: perl
    rule: http

  tasks:

   - name: Install httpd package
     yum: 
       name:
            - "{{ web_pkg }}"
            - "{{ firewall_pkg }}"
            - "{{ perl_pkg }}"
       state: latest

   - name: enable the service
     service:
       name:
             - "{{ web_pkg }}"
             - "{{ firewall_pkg }}"
             - "{{ perl_pkg }}"

       state: started

   - name: allow httpd package
     firewalld:
         service: "{{ rule }}"
         state: enabled
         permanent: yes  

